
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanquService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanquService {


    /**
     * 
     * @param codeCompte
     * @return
     *     returns ws.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws/", className = "ws.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws/", className = "ws.GetCompteResponse")
    @Action(input = "http://ws/BanquService/getCompteRequest", output = "http://ws/BanquService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "codeCompte", targetNamespace = "")
        Long codeCompte);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertEuroToDT", targetNamespace = "http://ws/", className = "ws.ConvertEuroToDT")
    @ResponseWrapper(localName = "convertEuroToDTResponse", targetNamespace = "http://ws/", className = "ws.ConvertEuroToDTResponse")
    @Action(input = "http://ws/BanquService/convertEuroToDTRequest", output = "http://ws/BanquService/convertEuroToDTResponse")
    public double convertEuroToDT(
        @WebParam(name = "Montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://ws/", className = "ws.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://ws/", className = "ws.GetComptesResponse")
    @Action(input = "http://ws/BanquService/getComptesRequest", output = "http://ws/BanquService/getComptesResponse")
    public List<Compte> getComptes();

}
